/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      animation: {
        customOverlay: "hideThenFadeIn 4s forwards",
        fadeIn: "fadeIn 1s ease-in-out",
        fadeInSlow: "fadeIn 2s ease-in-out",
        fadeInSlower: "fadeIn 5s ease-in-out",
        fadeInSlowDelay5: "fadeInDelay 5s ease-in-out",
        glitch1: "glitch1 10s infinite",
        glitch2: "glitch2 10s infinite",
        glitch3: "glitch3 10s infinite",
        flicker: "flicker 1s infinite",
        flicker2: "flicker 2s infinite",
        cascadeBottom: "cascadeBottom 60s infinite",
        cascadeBottomRight: "cascadeBottomRight 60s infinite",
        cascadeBottomLeft: "cascadeBottomLeft 60s infinite",
        cascadeTop: "cascadeTop 60s infinite",
        cascadeTopRight: "cascadeTopRight 60s infinite",
        cascadeTopLeft: "cascadeTopLeft 60s infinite",
        slideDownLeft: "slideDownLeft 5s forwards",
      },
      keyframes: {
        slideDownLeft: {
          "0%": { transform: "translate(0, 0)" },
          "100%": { transform: "translate(20%, 8vh)" },
        },
        cascadeBottom: {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(1000px)" },
        },
        cascadeBottomRight: {
          "0%": { transform: "translate(0, 0)" },
          "100%": { transform: "translate(1000px, 1000px)" },
        },
        cascadeBottomLeft: {
          "0%": { transform: "translate(0, 0)" },
          "100%": { transform: "translate(-1000px, 1000px)" },
        },
        cascadeTop: {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(-1000px)" },
        },
        cascadeTopRight: {
          "0%": { transform: "translate(0, 0)" },
          "100%": { transform: "translate(1000px, -1000px)" },
        },
        cascadeTopLeft: {
          "0%": { transform: "translate(0, 0)" },
          "100%": { transform: "translate(-1000px, -1000px)" },
        },
        flicker: {
          "0%, 19.999%, 22%, 62.999%, 64%, 64.999%, 70%, 100%": {
            opacity: 1,
          },
          "20%, 23%, 63%, 65%, 69%": {
            opacity: 0,
          },
        },
        hideThenFadeIn: {
          "0%": { opacity: 0 },
          "75%": { opacity: 0 },
          "100%": { opacity: 0.8 },
        },
        fadeIn: {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        fadeInDelay: {
          "0%": { opacity: 0 },
          "50%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        glitch1: {
          "0%": { transform: "none", opacity: "1" },
          "7%": { transform: "skew(-0.5deg, -0.9deg)", opacity: "0.75" },
          "9%": { transform: "none", opacity: "1" },
          "27%": { transform: "none", opacity: "1" },
          "30%": { transform: "skew(0.8deg, -0.1deg)", opacity: "0.75" },
          "33%": { transform: "none", opacity: "1" },
          "52%": { transform: "none", opacity: "1" },
          "55%": { transform: "skew(-1deg, 0.2deg)", opacity: "0.75" },
          "58%": { transform: "none", opacity: "1" },
          "72%": { transform: "none", opacity: "1" },
          "75%": { transform: "skew(0.4deg, 1deg)", opacity: "0.75" },
          "80%": { transform: "none", opacity: "1" },
          "100%": { transform: "none", opacity: "1" },
        },
        glitch2: {
          "0%": { transform: "none", opacity: "0.25" },
          "7%": { transform: "translate(-2px, -3px)", opacity: "0.5" },
          "9%": { transform: "none", opacity: "0.25" },
          "27%": { transform: "none", opacity: "0.25" },
          "30%": { transform: "translate(-5px, -2px)", opacity: "0.5" },
          "33%": { transform: "none", opacity: "0.25" },
          "52%": { transform: "none", opacity: "0.25" },
          "55%": { transform: "translate(-5px, -1px)", opacity: "0.5" },
          "58%": { transform: "none", opacity: "0.25" },
          "72%": { transform: "none", opacity: "0.25" },
          "75%": { transform: "translate(-2px, -6px)", opacity: "0.5" },
          "80%": { transform: "none", opacity: "0.25" },
          "100%": { transform: "none", opacity: "0.25" },
        },
        glitch3: {
          "0%": { transform: "none", opacity: "0.25" },
          "7%": { transform: "translate(2px, 3px)", opacity: "0.5" },
          "9%": { transform: "none", opacity: "0.25" },
          "27%": { transform: "none", opacity: "0.25" },
          "30%": { transform: "translate(5px, 2px)", opacity: "0.5" },
          "33%": { transform: "none", opacity: "0.25" },
          "52%": { transform: "none", opacity: "0.25" },
          "55%": { transform: "translate(5px, 1px)", opacity: "0.5" },
          "58%": { transform: "none", opacity: "0.25" },
          "72%": { transform: "none", opacity: "0.25" },
          "75%": { transform: "translate(2px, 6px)", opacity: "0.5" },
          "80%": { transform: "none", opacity: "0.25" },
          "100%": { transform: "none", opacity: "0.25" },
        },
      },
    },
  },
  plugins: [],
};
